menu:
  Home: /
  Archives: /archives
  Link: /link
  Ta: http://left.shooter.gl/

rss: /atom.xml

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname:

google_analytics:
favicon: /favicon.ico
